In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3] , dtype = 'int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3,4], [5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# Get Dimension

a.ndim # 'a' is a 1 dimensional array

1

In [6]:
b.ndim #'b' is a 2 dimesional array

2

In [7]:
# Shape
a.shape

(3,)

In [8]:
b.shape

(2, 4)

In [9]:
# Type

a.dtype

dtype('int16')

In [10]:
# Size

a.itemsize
# b.itemsize

2

In [11]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
b[0 , 1]

2

In [13]:
b[1:]

array([[5, 6, 7, 8]])

In [14]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
b[0, 1:3]

array([2, 3])

In [16]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.full([2,2], 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [19]:
np.full_like(b, 44)

array([[44, 44, 44, 44],
       [44, 44, 44, 44]])

In [20]:
# Random decimal Number 

np.random.rand(4,2)

array([[0.11737266, 0.45639564],
       [0.22324989, 0.35389746],
       [0.12397533, 0.17477106],
       [0.73627126, 0.02658062]])

In [21]:
# random integer Vale
np.random.randint(7, size = (3,3))

array([[3, 6, 5],
       [6, 1, 5],
       [3, 3, 0]])

In [22]:
# identity matrix

np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [23]:
output = np.ones([5,5])
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
z[1,1] = 1
print(z)


[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


In [26]:
output[1:4,1:4] = z

In [27]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
np.full((3,3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

Linear Alzebra

In [30]:
# Linear Algebra

a = np.arange(1,11).reshape(2,5)
print(a)

b= a.reshape(5,2)
print(b)

np.matmul(a,b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


array([[ 95, 110],
       [220, 260]])

In [31]:


# Find The Determinent

c = np. identity(5)
np.linalg.det(c)

1.0

Statistics

In [32]:
stats = np.arange(1,7).reshape(2,3)
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.min(stats, axis = 1)

array([1, 4])

In [ ]:
# Vertical Stacking

In [ ]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,0])

np.vstack((v1,v2))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [ ]:
# Horizontal stack

v3 = np.arange(1,5)
v4 = np.arange(1,5)

np.hstack((v3,v4))

array([1, 2, 3, 4, 1, 2, 3, 4])

Load Data From file


In [35]:
filedata = np.genfromtxt('text.txt', delimiter= ',')
filedata


array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14.]])

In [36]:
print(filedata[(filedata>9)])

[10. 11. 12. 13. 14.]
